apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: eu-west-3

nodeGroups:
  - name: node-group-1
    desiredCapacity: 3
    instanceType: t2.micro

fargateProfiles:
  - name: fargate-profile-1
    selectors:
      - namespace: default
