apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jane-cluster
  region: eu-west-3

nodeGroups:
  - name: my-node-group
    desiredCapacity: 3
    instanceType: t2.micro

fargateProfiles:
  - name: my-fargate-profile
    selectors:
      - namespace: my-app
