apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZDlaNDB5eHlrRlV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeE16QXhNalV6TXpGYUZ3MHpNekV4TWpjeE1qVTRNekZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMydExHMHBQcmV2TWp6R1Z6bkp0NHNFTHA2empkenRrS2oxbHVOV0lYWUU5RFBqWmNPeFhlSTR5NGoKOUVqUnIwR3QrSWJwbHY5RGNJckYrdEFEajBRTEdmM0tpR096cWpndUE1blVPbmFUSE9RUytrcE5LVnpCR2R1NgpINE9MWUpneWU5U05YbWRQcDg3UnEyeGJic0NoRi85MHlyRzViczV1cXhTNkxPZFRQWU9seVIxV0lXUWY1Z2RWClZzS3YwbUJLVGdIR01PY0lwcERpZmt3VmRxK1RKcU5JdEtud1FzbGRLbzh0R2JmUEZuV2UyeHcrT2lYMzJ4eU8KVXZvck1CQkFSb1lVSVVCUlFNMTlLejVQbC9TSzBhR3N0RHgrdGJBL3VWWFNvVyt6bERJTjdzTTBpY1EvQytoSAp3aitodVJzZHNMMnJ0dlQzelJTNk5nVFVLVmVIQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRMEdNUC9ISG02U24zSWlBQ2hYNzg3M3hJVGREQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQk5YNnVVMnRiMwpHbDVDV05WSStyZ1ZUMVdZNzJkOTExdjh4a3czV1RSOFNxM0tHbTA0TzUzSHpsMFlhYWQrbjBkSDVqdWE5dUxMCjgrNUxabE1Eakd5UTNlSnVodEZiUmJqNTlFQ1ZudG9wdGVKc0pnWFF6Q25QRkdVNWVXa05yK1kvMXVYcmljVWMKekQ2VUlZRGJNRy9wbmsrVXk1L2RJRERJdTJ4M0pLaVNtTFNsRm04YVIzMFJuQ3p3dVhNMnYxUjNZUnNyaXU3OQp4dmpTNjdlMVRHYzNjVDROUHUxT2hyK3JiZ0xDMDMvcnpXNi9vRmpiM2doQTVZbnRkRzZTRXVRMnIxblZnTEpOCi9QelNJMEtVbDF2WHRWNkNJYlR3cjYydHRQZGNYS0h2QndlaW0rbityajlSOUlwUkY3aTY4aWw0bFcrbUFyKy8KM1RqRExzTENBZmQ4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://4FB2B6824DAADC99BF729BBEB1D7C500.yl4.eu-west-3.eks.amazonaws.com
  name: jane-cluster.eu-west-3.eksctl.io
contexts:
- context:
    cluster: jane-cluster.eu-west-3.eksctl.io
    user: julia@jane-cluster.eu-west-3.eksctl.io
  name: julia@jane-cluster.eu-west-3.eksctl.io
current-context: julia@jane-cluster.eu-west-3.eksctl.io
kind: Config
preferences: {}
users:
- name: julia@jane-cluster.eu-west-3.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - jane-cluster
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: eu-west-3
      provideClusterInfo: false
