apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:5
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: PMA_HOST # Use the hostname of your MySQL service
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: db_server
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: db_root_pwd


---

apiVersion: v1

kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 8081    # The external port you want to use
      targetPort: 80  # The container port (phpMyAdmin's default port)
      nodePort: 30000
  type: LoadBalancer # will be open to public like this
